name: divbook
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_storage: ^3.1.1
  firebase_auth: ^0.11.1
  google_fonts: ^0.2.0
  url_launcher: ^5.0.2
  flutter_launcher_icons: ^0.7.4

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in : ^ 4.1.1
  fluttertoast: ^3.0.1
  sqflite: any
  path_provider: ^1.5.0
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.11.0+2
  image_picker: ^0.6.3+1
  flutter_speed_dial: ^1.2.5
  bottom_navy_bar: ^5.3.2
  flutter_sparkline: "^0.1.0"
  flutter_staggered_grid_view: "^0.3.0"
  flutter_circular_chart: ^0.1.0
  font_awesome_flutter: ^8.2.0
  scoped_model: ^1.0.1
  charts_flutter: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/person.png
  - assets/personq.png
  - assets/produto.png
  - assets/google.jpg

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icone.png"